const data = {
  'sale_ratio': 0.5,
  'name_pinyin': 'baoheye|0.5jin',
  'sale_unit_price': 581,
  'driver': {'source_driver_name': null, 'name': '*自营司机'},
  'sort_id_format': 3,
  'remark': '这是备注，这是备注',
  'category_id_1': 'A6153',
  'std_sale_price': 1162,
  'order': {
    'source_address_id': null,
    'id': 'LK1721339',
    'receiver_name': '小麦',
    'source_address_name': null,
    'source_sort_id': null,
    'batch_remark': '',
    'station_id': 'T12071',
    'address_name': '南山-某商户',
    'sort_id': 3,
    'address_id': 'T12483',
    'station_name': '某仓',
    'route_name': '路线1'
  },
  'phone': '400-686-3376',
  'category_id_2': 'B29921',
  'out_of_stock': false,
  'real_quantity': 2.0,
  'quantity': 2.0,
  'weighting_quantity': 1.0,
  'is_weight': true,
  'sale_unit_name': '袋',
  'id': 'D3516105',
  'name': '薄荷叶|0.5斤',
  'has_weighted': true,
  'spu_id': 'C1174415',
  'driver_pinyin': '*ziying',
  'std_unit_name': '斤'
}

export default data
